### ISSUE TITLE
Pause button not working

### ISSUE THREAD

**Issue by eduraga** [eduraga/feeler#112]
Pausing a session only sometimes will pause the log, the timer, and only sometimes will switch the play/pause button.

**Comment by eduraga** [comment]
Not working yet. When pressing "pause" the counter keeps working. Once pressing "pause", that button becomes "play" and there's no way to go back to the original state. Even if one stops the recording or logs out, the button appears as "play"

**Comment by autotel** [comment]
could we hide the pause button for now?

**Comment by eduraga** [comment]
Yes, that option is fine
